[project]
name = "amortsched"
dynamic = ["version"]
description = "Amortization schedule generator API"
readme = "README.md"
requires-python = ">=3.14,<4.0"
dependencies = [
  "fastapi[standard-no-fastapi-cloud-cli]",
  "uvicorn[standard]",
  "python-multipart",
  "pydantic",
  "pydantic-settings",
  "sqlalchemy[asyncio]",
  "psycopg[binary]",
  "alembic",
  "structlog",
  "pyjwt",
  "redis>=8.1.0",
]

[project.optional-dependencies]
prod = ["gunicorn", "uvicorn-worker"]

[dependency-groups]
test = [
  "pytest",
  "anyio",
  "pytest-sugar",
  "pytest-cov",
  "httpx2",
  "faker",
  "factory-boy",
  "pytest-factoryboy",
  "testcontainers",
]
lint = ["ruff", "basedpyright"]
dev = [
  "debugpy",
  "icecream",
  "ipython",
  { include-group = "lint" },
  { include-group = "test" },
]

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.hatch.build.targets.wheel]
packages = ["src/amortsched"]

[tool.hatch.build.hooks.version]
path = "src/amortsched/_version.py"
template = '''version = "{version}"
'''

[tool.uv]
exclude-newer = "1 week"
exclude-newer-package = { ruff = "1 day" }
default-groups = "all"
cache-keys = [{ file = "pyproject.toml" }, { git = { commit = true, tags = true } }]

[tool.uv-dynamic-versioning]
fallback-version = "0.0.0"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "W", "C90", "B", "I"]
ignore = ["B008"]

[tool.pytest.ini_options]
addopts = "--import-mode=importlib --verbose --color=yes --tb=short --maxfail=5"
testpaths = ["tests"]

[tool.coverage.run]
source = ["amortsched"]
branch = true

[tool.coverage.report]
show_missing = true

[tool.basedpyright]
typeCheckingMode = "standard"
pythonVersion = "3.14"
pythonPlatform = "Linux"
include = ["src"]
extraPaths = ["src"]
reportMissingImports = false
reportMissingTypeStubs = false
