import uuid
from types import TracebackType
from typing import Protocol, Self

from amortsched.core.entities import Plan, Profile, Schedule, User
from amortsched.core.repositories import AsyncRepository


class SecuritySettings(Protocol):
    @property
    def secret_key(self) -> str: ...
    @property
    def token_expiration_minutes(self) -> int: ...
    @property
    def refresh_token_expiration_days(self) -> int: ...


class DatabaseSettings(Protocol):
    @property
    def url(self) -> str: ...


class Settings(Protocol):
    @property
    def security(self) -> SecuritySettings: ...
    @property
    def database(self) -> DatabaseSettings: ...
    @property
    def debug(self) -> bool: ...


class TokenService(Protocol):
    def create_access_token(self, user_id: uuid.UUID) -> str: ...
    def decode_access_token(self, token: str) -> uuid.UUID: ...
    def create_refresh_token(self) -> str: ...
    def hash_refresh_token(self, token: str) -> str: ...


class AsyncUnitOfWork(Protocol):
    users: AsyncRepository[User]
    profiles: AsyncRepository[Profile]
    plans: AsyncRepository[Plan]
    schedules: AsyncRepository[Schedule]

    async def begin(self) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def close(self) -> None: ...

    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> bool | None: ...
